@startuml
actor User
participant Launcher
participant MainAPP
participant FXMLLoader as FXML
participant "WelcomeController" as WC
participant "DatabaseManager" as DB
participant "TableController" as TC
participant Stage

User -> Launcher: main()
Launcher -> MainAPP: main()
MainAPP -> MainAPP: start(Stage)
MainAPP -> FXML: load(welcome.fxml)
FXML -> WC: initialize()
MainAPP -> WC: setStage(Stage)
MainAPP -> Stage: setScene(welcome)\nshow()

User -> WC: wpisuje username\nklik ENTER
WC -> DB: getBalance(username)
alt użytkownik nie istnieje
  WC -> DB: saveOrUpdateUser(username, 1000)
end

WC -> FXML: load(table.fxml)
FXML -> TC: initialize()
WC -> TC: setLoggedUser(username)
WC -> TC: initializePlayerBalance(balance)

WC -> Stage: getScene().setRoot(tableRoot)\nsetWidth/Height\ncenterOnScreen
@enduml